language: python

cache:
  pip: true
  directories:
    - "$HOME/.cache/pip"

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10-dev
  - nightly

jobs:
  allow_failures:
    - python: 3.10-dev
    - python: nightly

before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - sh unittest.sh

#deploy:
#  provider: pypi
#  username: "$PYPI_USERNAME"
#  password: "$PYPI_PASSWORD"
#  skip_existing: true
#  on:
#    tags: true
#    python: 3.9